<?php
/**
 * Inline SVG icons.
 *
 * @package Hamista\Core
 */

namespace Hamista\Core\Support;

defined( 'ABSPATH' ) || exit;

/**
 * Lucide UI icons (24×24, `currentColor` stroke) and Simple Icons brand marks.
 *
 * Names: Lucide names (`check`, `shopping-cart`, …) resolve first. Brand
 * slugs (`instagram`, `telegram`, …) resolve when no Lucide icon has the
 * same name; `brand-{slug}` always selects the brand. Only `x` collides:
 * `x` is the close icon, `brand-x` is the X (Twitter) logo.
 *
 * Output: `<svg class="hm-icon hm-icon--{name}" aria-hidden="true" …>`.
 * Directional icons (arrows, chevrons, log-out, send) also get
 * `hm-icon--dir`, which the UI CSS mirrors in RTL.
 *
 * Data files are generated by tools/icons/generate-icons.mjs.
 *
 * @since 1.0.0
 */
final class Icons {

	/**
	 * Icons that point in the reading direction and are mirrored in RTL.
	 */
	private const DIRECTIONAL = [ 'arrow-left', 'arrow-right', 'arrow-up-right', 'chevron-left', 'chevron-right', 'log-out', 'send' ];

	/**
	 * Lucide markup by name, loaded on first use.
	 *
	 * @var array<string, string>|null
	 */
	private static ?array $lucide = null;

	/**
	 * Brand path data by slug, loaded on first use.
	 *
	 * @var array<string, string>|null
	 */
	private static ?array $brands = null;

	/**
	 * Returns an inline SVG icon.
	 *
	 * Special `$attrs` keys:
	 * - `title`: accessible name; the icon gets `role="img"`, `aria-label`
	 *   and a `<title>` instead of `aria-hidden`.
	 * - `class`: extra classes (string or array).
	 * - `size`: width and height in px (default 24; CSS sizes `.hm-icon` to 1em).
	 * - `flip`: true/false forces RTL mirroring on or off.
	 * Any other key is printed as an SVG attribute (escaped), e.g. `stroke-width`.
	 *
	 * @since 1.0.0
	 *
	 * @param string $name  Icon name.
	 * @param array  $attrs Attributes.
	 * @return string SVG markup, or '' for unknown names.
	 */
	public static function get( string $name, array $attrs = [] ): string {
		$icon = self::lookup( strtolower( trim( $name ) ) );
		if ( null === $icon ) {
			return '';
		}
		[ $set, $slug, $body ] = $icon;

		$title = isset( $attrs['title'] ) ? trim( (string) $attrs['title'] ) : '';
		$size  = isset( $attrs['size'] ) ? max( 1, (int) $attrs['size'] ) : 24;
		$flip  = array_key_exists( 'flip', $attrs ) ? (bool) $attrs['flip'] : ( 'lucide' === $set && in_array( $slug, self::DIRECTIONAL, true ) );
		$extra = isset( $attrs['class'] ) ? (array) $attrs['class'] : [];
		unset( $attrs['title'], $attrs['size'], $attrs['flip'], $attrs['class'] );

		$svg = [
			'class'   => array_merge( [ 'hm-icon', 'hm-icon--' . $slug, 'brand' === $set ? 'hm-icon--brand' : '', $flip ? 'hm-icon--dir' : '' ], array_map( 'strval', $extra ) ),
			'xmlns'   => 'http://www.w3.org/2000/svg',
			'width'   => $size,
			'height'  => $size,
			'viewBox' => '0 0 24 24',
		];
		if ( 'brand' === $set ) {
			$svg['fill'] = 'currentColor';
		} else {
			$svg += [
				'fill'            => 'none',
				'stroke'          => 'currentColor',
				'stroke-width'    => 2,
				'stroke-linecap'  => 'round',
				'stroke-linejoin' => 'round',
			];
		}
		if ( '' === $title ) {
			$svg['aria-hidden'] = 'true';
			$svg['focusable']   = 'false';
		} else {
			$svg['role']       = 'img';
			$svg['aria-label'] = $title;
		}

		$svg = array_merge( $svg, $attrs );

		return '<svg' . Html::attrs( $svg ) . '>'
			. ( '' === $title ? '' : '<title>' . esc_html( $title ) . '</title>' )
			. $body
			. '</svg>';
	}

	/**
	 * Whether an icon name resolves.
	 *
	 * @since 1.0.0
	 *
	 * @param string $name Icon name.
	 * @return bool
	 */
	public static function has( string $name ): bool {
		return null !== self::lookup( strtolower( trim( $name ) ) );
	}

	/**
	 * Every icon name, for icon pickers: Lucide names, then `brand-{slug}` names.
	 *
	 * @since 1.0.0
	 *
	 * @return string[]
	 */
	public static function names(): array {
		return array_merge(
			array_keys( self::lucide() ),
			array_map( static fn( string $slug ): string => 'brand-' . $slug, array_keys( self::brands() ) )
		);
	}

	/**
	 * Resolves a name to [ set, slug, inner markup ].
	 *
	 * @param string $name Lower-cased name.
	 * @return array{0:string,1:string,2:string}|null
	 */
	private static function lookup( string $name ): ?array {
		if ( str_starts_with( $name, 'brand-' ) ) {
			$slug = substr( $name, 6 );
			return isset( self::brands()[ $slug ] ) ? [ 'brand', $slug, self::brand_markup( $slug ) ] : null;
		}
		if ( isset( self::lucide()[ $name ] ) ) {
			return [ 'lucide', $name, self::lucide()[ $name ] ];
		}
		if ( isset( self::brands()[ $name ] ) ) {
			return [ 'brand', $name, self::brand_markup( $name ) ];
		}
		return null;
	}

	/**
	 * `<path>` element of a brand icon.
	 *
	 * @param string $slug Brand slug.
	 * @return string
	 */
	private static function brand_markup( string $slug ): string {
		return '<path d="' . esc_attr( self::brands()[ $slug ] ) . '"/>';
	}

	/**
	 * Lucide data.
	 *
	 * @return array<string, string>
	 */
	private static function lucide(): array {
		if ( null === self::$lucide ) {
			self::$lucide = (array) require __DIR__ . '/icons/lucide.php';
		}
		return self::$lucide;
	}

	/**
	 * Brand data.
	 *
	 * @return array<string, string>
	 */
	private static function brands(): array {
		if ( null === self::$brands ) {
			self::$brands = (array) require __DIR__ . '/icons/brands.php';
		}
		return self::$brands;
	}
}
